blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/username/csv2json/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/username/csv2json/blob/main/README.md
    about: Check the documentation before reporting issues.