// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.1
// source: admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity of an error
type Severity int32

const (
	// A warning, OK to proceed
	Severity_WARN Severity = 0
	// Critical error, action has to be taken
	Severity_CRITICAL Severity = 1
	// Fatal error, an operator should be informed
	Severity_FATAL Severity = 2
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "WARN",
		1: "CRITICAL",
		2: "FATAL",
	}
	Severity_value = map[string]int32{
		"WARN":     0,
		"CRITICAL": 1,
		"FATAL":    2,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

// What format to use
type OutputType int32

const (
	// JSON output
	OutputType_JSON OutputType = 0
	// YAML output
	OutputType_YAML OutputType = 1
	// TOML output
	OutputType_TOML OutputType = 2
)

// Enum value maps for OutputType.
var (
	OutputType_name = map[int32]string{
		0: "JSON",
		1: "YAML",
		2: "TOML",
	}
	OutputType_value = map[string]int32{
		"JSON": 0,
		"YAML": 1,
		"TOML": 2,
	}
)

func (x OutputType) Enum() *OutputType {
	p := new(OutputType)
	*p = x
	return p
}

func (x OutputType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputType) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[1].Descriptor()
}

func (OutputType) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[1]
}

func (x OutputType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputType.Descriptor instead.
func (OutputType) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

// Render as data type
type FieldType int32

const (
	// a string
	FieldType_STRING FieldType = 0
	// an integer
	FieldType_INT FieldType = 1
	// A floating point value
	FieldType_FLOAT FieldType = 2
	// a boolean value
	FieldType_BOOL FieldType = 3
)

// Enum value maps for FieldType.
var (
	FieldType_name = map[int32]string{
		0: "STRING",
		1: "INT",
		2: "FLOAT",
		3: "BOOL",
	}
	FieldType_value = map[string]int32{
		"STRING": 0,
		"INT":    1,
		"FLOAT":  2,
		"BOOL":   3,
	}
)

func (x FieldType) Enum() *FieldType {
	p := new(FieldType)
	*p = x
	return p
}

func (x FieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[2].Descriptor()
}

func (FieldType) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[2]
}

func (x FieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FieldType.Descriptor instead.
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

// was mapping added or updated
type ActionTaken int32

const (
	// Added
	ActionTaken_ADDED ActionTaken = 0
	// updated
	ActionTaken_UPDATED ActionTaken = 1
)

// Enum value maps for ActionTaken.
var (
	ActionTaken_name = map[int32]string{
		0: "ADDED",
		1: "UPDATED",
	}
	ActionTaken_value = map[string]int32{
		"ADDED":   0,
		"UPDATED": 1,
	}
)

func (x ActionTaken) Enum() *ActionTaken {
	p := new(ActionTaken)
	*p = x
	return p
}

func (x ActionTaken) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionTaken) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[3].Descriptor()
}

func (ActionTaken) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[3]
}

func (x ActionTaken) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionTaken.Descriptor instead.
func (ActionTaken) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

// What kind of calculation takes part
type Kind int32

const (
	// Run specific information such as record number or number of records
	Kind_APPLICATION Kind = 0
	// Date and time rendered
	Kind_DATETIME Kind = 1
	// Environment variables
	Kind_ENVRINMENT Kind = 2
	// Extra variable
	Kind_EXTRA Kind = 3
	// Map values to other values
	Kind_MAPPING Kind = 4
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "APPLICATION",
		1: "DATETIME",
		2: "ENVRINMENT",
		3: "EXTRA",
		4: "MAPPING",
	}
	Kind_value = map[string]int32{
		"APPLICATION": 0,
		"DATETIME":    1,
		"ENVRINMENT":  2,
		"EXTRA":       3,
		"MAPPING":     4,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[4].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[4]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

// Location to put calculated fiels
type Location int32

const (
	// to each record
	Location_RECORD Location = 0
	// to documsnt, only has an effect when generating an array
	Location_EOCUMENT Location = 1
)

// Enum value maps for Location.
var (
	Location_name = map[int32]string{
		0: "RECORD",
		1: "EOCUMENT",
	}
	Location_value = map[string]int32{
		"RECORD":   0,
		"EOCUMENT": 1,
	}
)

func (x Location) Enum() *Location {
	p := new(Location)
	*p = x
	return p
}

func (x Location) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Location) Descriptor() protoreflect.EnumDescriptor {
	return file_admin_proto_enumTypes[5].Descriptor()
}

func (Location) Type() protoreflect.EnumType {
	return &file_admin_proto_enumTypes[5]
}

func (x Location) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Location.Descriptor instead.
func (Location) EnumDescriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

// An operation has not run run smoothly
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A message denoting what happened
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Severity of incident, see enum desacription
	Severity Severity `protobuf:"varint,2,opt,name=severity,proto3,enum=Severity" json:"severity,omitempty"`
	// Any additional - if any that is
	AdditionalInformation *string `protobuf:"bytes,3,opt,name=additional_information,json=additionalInformation,proto3,oneof" json:"additional_information,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_WARN
}

func (x *Error) GetAdditionalInformation() string {
	if x != nil && x.AdditionalInformation != nil {
		return *x.AdditionalInformation
	}
	return ""
}

// All data to create a project
type CreateProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the project
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// A description which can be used to display information
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// What rofmat to use (can be overriddeh in a run later)
	OutputType *OutputType `protobuf:"varint,10,opt,name=output_type,json=outputType,proto3,enum=OutputType,oneof" json:"output_type,omitempty"`
	// Access CSV fields by name
	Named *bool `protobuf:"varint,11,opt,name=named,proto3,oneof" json:"named,omitempty"`
	// Output an array
	Array *bool `protobuf:"varint,12,opt,name=array,proto3,oneof" json:"array,omitempty"`
	// If output is an array, how to call the property
	NestedPropertyName *string `protobuf:"bytes,13,opt,name=nested_property_name,json=nestedPropertyName,proto3,oneof" json:"nested_property_name,omitempty"`
	// What separator is used in CSV
	Separator     *string `protobuf:"bytes,14,opt,name=separator,proto3,oneof" json:"separator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectRequest) Reset() {
	*x = CreateProjectRequest{}
	mi := &file_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectRequest) ProtoMessage() {}

func (x *CreateProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectRequest.ProtoReflect.Descriptor instead.
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProjectRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateProjectRequest) GetOutputType() OutputType {
	if x != nil && x.OutputType != nil {
		return *x.OutputType
	}
	return OutputType_JSON
}

func (x *CreateProjectRequest) GetNamed() bool {
	if x != nil && x.Named != nil {
		return *x.Named
	}
	return false
}

func (x *CreateProjectRequest) GetArray() bool {
	if x != nil && x.Array != nil {
		return *x.Array
	}
	return false
}

func (x *CreateProjectRequest) GetNestedPropertyName() string {
	if x != nil && x.NestedPropertyName != nil {
		return *x.NestedPropertyName
	}
	return ""
}

func (x *CreateProjectRequest) GetSeparator() string {
	if x != nil && x.Separator != nil {
		return *x.Separator
	}
	return ""
}

// Result of creating a project
type CreateProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	// id if projecb was created
	Id            *string `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProjectResponse) Reset() {
	*x = CreateProjectResponse{}
	mi := &file_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProjectResponse) ProtoMessage() {}

func (x *CreateProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProjectResponse.ProtoReflect.Descriptor instead.
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CreateProjectResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *CreateProjectResponse) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

// Remove a project and all related data
type RemoveProjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectRequest) Reset() {
	*x = RemoveProjectRequest{}
	mi := &file_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectRequest) ProtoMessage() {}

func (x *RemoveProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectRequest.ProtoReflect.Descriptor instead.
func (*RemoveProjectRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveProjectRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// Result of removal
type RemoveProjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors        []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProjectResponse) Reset() {
	*x = RemoveProjectResponse{}
	mi := &file_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProjectResponse) ProtoMessage() {}

func (x *RemoveProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProjectResponse.ProtoReflect.Descriptor instead.
func (*RemoveProjectResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveProjectResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Data returned per project for a list request
type ListProjectData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uniqud identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of project
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description for more information
	Description   *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectData) Reset() {
	*x = ListProjectData{}
	mi := &file_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectData) ProtoMessage() {}

func (x *ListProjectData) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectData.ProtoReflect.Descriptor instead.
func (*ListProjectData) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListProjectData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListProjectData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListProjectData) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// Request to get all projects
type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{6}
}

// List of projects
type ListProjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	// Projects known
	Projects      []*ListProjectData `protobuf:"bytes,2,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListProjectsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ListProjectsResponse) GetProjects() []*ListProjectData {
	if x != nil {
		return x.Projects
	}
	return nil
}

// ColumnConfiguration is a simple mapping from column to proprty
type ColumnConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Property to map to
	Property string `protobuf:"bytes,1,opt,name=property,proto3" json:"property,omitempty"`
	// data type to render
	Type          FieldType `protobuf:"varint,2,opt,name=type,proto3,enum=FieldType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnConfiguration) Reset() {
	*x = ColumnConfiguration{}
	mi := &file_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnConfiguration) ProtoMessage() {}

func (x *ColumnConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnConfiguration.ProtoReflect.Descriptor instead.
func (*ColumnConfiguration) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ColumnConfiguration) GetProperty() string {
	if x != nil {
		return x.Property
	}
	return ""
}

func (x *ColumnConfiguration) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_STRING
}

// Add one or more mappings. If a mapping exists will be overwritten
type AddOrUpdateMappingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// Mappings to add or update, string is the column either by name (project is named) or index
	Mappings      map[string]*ColumnConfiguration `protobuf:"bytes,2,rep,name=mappings,proto3" json:"mappings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateMappingRequest) Reset() {
	*x = AddOrUpdateMappingRequest{}
	mi := &file_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateMappingRequest) ProtoMessage() {}

func (x *AddOrUpdateMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateMappingRequest.ProtoReflect.Descriptor instead.
func (*AddOrUpdateMappingRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{9}
}

func (x *AddOrUpdateMappingRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *AddOrUpdateMappingRequest) GetMappings() map[string]*ColumnConfiguration {
	if x != nil {
		return x.Mappings
	}
	return nil
}

// Result of adding or updating
type AddOrUpdateMappingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	// Actions taken per column by name or index
	ActionsTaken  map[string]ActionTaken `protobuf:"bytes,2,rep,name=ActionsTaken,proto3" json:"ActionsTaken,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=ActionTaken"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateMappingResponse) Reset() {
	*x = AddOrUpdateMappingResponse{}
	mi := &file_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateMappingResponse) ProtoMessage() {}

func (x *AddOrUpdateMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateMappingResponse.ProtoReflect.Descriptor instead.
func (*AddOrUpdateMappingResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AddOrUpdateMappingResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *AddOrUpdateMappingResponse) GetActionsTaken() map[string]ActionTaken {
	if x != nil {
		return x.ActionsTaken
	}
	return nil
}

// Request to get all mappings fo a project
type ListMappingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMappingsRequest) Reset() {
	*x = ListMappingsRequest{}
	mi := &file_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMappingsRequest) ProtoMessage() {}

func (x *ListMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMappingsRequest.ProtoReflect.Descriptor instead.
func (*ListMappingsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ListMappingsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// List of projects
type ListMappingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	// Mappings, string is the column either by name (project is named) or index
	Mappings      map[string]*ColumnConfiguration `protobuf:"bytes,2,rep,name=mappings,proto3" json:"mappings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMappingsResponse) Reset() {
	*x = ListMappingsResponse{}
	mi := &file_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMappingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMappingsResponse) ProtoMessage() {}

func (x *ListMappingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMappingsResponse.ProtoReflect.Descriptor instead.
func (*ListMappingsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListMappingsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ListMappingsResponse) GetMappings() map[string]*ColumnConfiguration {
	if x != nil {
		return x.Mappings
	}
	return nil
}

type RemoveMappingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// which mapping(s) to remove
	Mappings      []string `protobuf:"bytes,2,rep,name=mappings,proto3" json:"mappings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMappingRequest) Reset() {
	*x = RemoveMappingRequest{}
	mi := &file_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMappingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMappingRequest) ProtoMessage() {}

func (x *RemoveMappingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMappingRequest.ProtoReflect.Descriptor instead.
func (*RemoveMappingRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveMappingRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RemoveMappingRequest) GetMappings() []string {
	if x != nil {
		return x.Mappings
	}
	return nil
}

// Result of removing mapping(s)
type RemoveMappingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors        []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMappingResponse) Reset() {
	*x = RemoveMappingResponse{}
	mi := &file_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMappingResponse) ProtoMessage() {}

func (x *RemoveMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMappingResponse.ProtoReflect.Descriptor instead.
func (*RemoveMappingResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveMappingResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

// add one or more extra variables
type AddExtraVariableRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// Variables to add
	ExtraVariables map[string]string `protobuf:"bytes,2,rep,name=extra_variables,json=extraVariables,proto3" json:"extra_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddExtraVariableRequest) Reset() {
	*x = AddExtraVariableRequest{}
	mi := &file_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExtraVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExtraVariableRequest) ProtoMessage() {}

func (x *AddExtraVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExtraVariableRequest.ProtoReflect.Descriptor instead.
func (*AddExtraVariableRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{15}
}

func (x *AddExtraVariableRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *AddExtraVariableRequest) GetExtraVariables() map[string]string {
	if x != nil {
		return x.ExtraVariables
	}
	return nil
}

// Result of adding extra variable(s)
type AddExtraVariableResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors        []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddExtraVariableResponse) Reset() {
	*x = AddExtraVariableResponse{}
	mi := &file_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddExtraVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddExtraVariableResponse) ProtoMessage() {}

func (x *AddExtraVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddExtraVariableResponse.ProtoReflect.Descriptor instead.
func (*AddExtraVariableResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{16}
}

func (x *AddExtraVariableResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Request to get all mappings fo a project
type ListExtraVariablesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExtraVariablesRequest) Reset() {
	*x = ListExtraVariablesRequest{}
	mi := &file_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExtraVariablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExtraVariablesRequest) ProtoMessage() {}

func (x *ListExtraVariablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExtraVariablesRequest.ProtoReflect.Descriptor instead.
func (*ListExtraVariablesRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ListExtraVariablesRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// List of projects
type ListExtraVariablesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	// Extra variables, string is the name
	ExtraVariables map[string]string `protobuf:"bytes,2,rep,name=extra_variables,json=extraVariables,proto3" json:"extra_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListExtraVariablesResponse) Reset() {
	*x = ListExtraVariablesResponse{}
	mi := &file_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExtraVariablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExtraVariablesResponse) ProtoMessage() {}

func (x *ListExtraVariablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExtraVariablesResponse.ProtoReflect.Descriptor instead.
func (*ListExtraVariablesResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ListExtraVariablesResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ListExtraVariablesResponse) GetExtraVariables() map[string]string {
	if x != nil {
		return x.ExtraVariables
	}
	return nil
}

type RemoveExtraVariableRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// which mapping(s) to remove
	ExtraVariables []string `protobuf:"bytes,2,rep,name=extra_variables,json=extraVariables,proto3" json:"extra_variables,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveExtraVariableRequest) Reset() {
	*x = RemoveExtraVariableRequest{}
	mi := &file_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveExtraVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveExtraVariableRequest) ProtoMessage() {}

func (x *RemoveExtraVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveExtraVariableRequest.ProtoReflect.Descriptor instead.
func (*RemoveExtraVariableRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveExtraVariableRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RemoveExtraVariableRequest) GetExtraVariables() []string {
	if x != nil {
		return x.ExtraVariables
	}
	return nil
}

// Result of removing mapping(s)
type RemoveExtraVariableResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors        []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveExtraVariableResponse) Reset() {
	*x = RemoveExtraVariableResponse{}
	mi := &file_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveExtraVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveExtraVariableResponse) ProtoMessage() {}

func (x *RemoveExtraVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveExtraVariableResponse.ProtoReflect.Descriptor instead.
func (*RemoveExtraVariableResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveExtraVariableResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

// describes a calculated field
type CalculatedField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kind denotes what kind of calculate has to be treated
	Kind Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=Kind" json:"kind,omitempty"`
	// Format denotes a formatting value or the value to acquire
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// Type informa about the type represented
	Type FieldType `protobuf:"varint,3,opt,name=type,proto3,enum=FieldType" json:"type,omitempty"`
	// Location specifies the location or context where the calculated field applies in the mapping.
	// Either document or record
	Location      Location `protobuf:"varint,4,opt,name=location,proto3,enum=Location" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatedField) Reset() {
	*x = CalculatedField{}
	mi := &file_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatedField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatedField) ProtoMessage() {}

func (x *CalculatedField) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatedField.ProtoReflect.Descriptor instead.
func (*CalculatedField) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{21}
}

func (x *CalculatedField) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_APPLICATION
}

func (x *CalculatedField) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CalculatedField) GetType() FieldType {
	if x != nil {
		return x.Type
	}
	return FieldType_STRING
}

func (x *CalculatedField) GetLocation() Location {
	if x != nil {
		return x.Location
	}
	return Location_RECORD
}

// Add one or more calculated fields to the project
type AddOrUpdateCalculatedFieldsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// field to add, string key is the field name
	CalculatedFields map[string]*CalculatedField `protobuf:"bytes,2,rep,name=calculated_fields,json=calculatedFields,proto3" json:"calculated_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddOrUpdateCalculatedFieldsRequest) Reset() {
	*x = AddOrUpdateCalculatedFieldsRequest{}
	mi := &file_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateCalculatedFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateCalculatedFieldsRequest) ProtoMessage() {}

func (x *AddOrUpdateCalculatedFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateCalculatedFieldsRequest.ProtoReflect.Descriptor instead.
func (*AddOrUpdateCalculatedFieldsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{22}
}

func (x *AddOrUpdateCalculatedFieldsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *AddOrUpdateCalculatedFieldsRequest) GetCalculatedFields() map[string]*CalculatedField {
	if x != nil {
		return x.CalculatedFields
	}
	return nil
}

// Response to add calculated fields
type AddOrUpdateCalculatedFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors        []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateCalculatedFieldsResponse) Reset() {
	*x = AddOrUpdateCalculatedFieldsResponse{}
	mi := &file_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateCalculatedFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateCalculatedFieldsResponse) ProtoMessage() {}

func (x *AddOrUpdateCalculatedFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateCalculatedFieldsResponse.ProtoReflect.Descriptor instead.
func (*AddOrUpdateCalculatedFieldsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{23}
}

func (x *AddOrUpdateCalculatedFieldsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type RemoveCalculatedFieldsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	// which mapping(s) to remove
	CalculatedFields []string `protobuf:"bytes,2,rep,name=calculated_fields,json=calculatedFields,proto3" json:"calculated_fields,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveCalculatedFieldsRequest) Reset() {
	*x = RemoveCalculatedFieldsRequest{}
	mi := &file_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCalculatedFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCalculatedFieldsRequest) ProtoMessage() {}

func (x *RemoveCalculatedFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCalculatedFieldsRequest.ProtoReflect.Descriptor instead.
func (*RemoveCalculatedFieldsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveCalculatedFieldsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RemoveCalculatedFieldsRequest) GetCalculatedFields() []string {
	if x != nil {
		return x.CalculatedFields
	}
	return nil
}

// Result of removing mapping(s)
type RemoveCalculatedFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors        []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCalculatedFieldsResponse) Reset() {
	*x = RemoveCalculatedFieldsResponse{}
	mi := &file_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCalculatedFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCalculatedFieldsResponse) ProtoMessage() {}

func (x *RemoveCalculatedFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCalculatedFieldsResponse.ProtoReflect.Descriptor instead.
func (*RemoveCalculatedFieldsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{25}
}

func (x *RemoveCalculatedFieldsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

// Request to get all mappings fo a project
type ListCalculatedFieldsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// reference to project
	Project       string `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCalculatedFieldsRequest) Reset() {
	*x = ListCalculatedFieldsRequest{}
	mi := &file_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCalculatedFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCalculatedFieldsRequest) ProtoMessage() {}

func (x *ListCalculatedFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCalculatedFieldsRequest.ProtoReflect.Descriptor instead.
func (*ListCalculatedFieldsRequest) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{26}
}

func (x *ListCalculatedFieldsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

// List of projects
type ListCalculatedFieldsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any errors
	Errors []*Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	// Calculated feilds, string is the field either by name (project is named) or index
	CalculatedFields map[string]*CalculatedField `protobuf:"bytes,2,rep,name=calculated_fields,json=calculatedFields,proto3" json:"calculated_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListCalculatedFieldsResponse) Reset() {
	*x = ListCalculatedFieldsResponse{}
	mi := &file_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCalculatedFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCalculatedFieldsResponse) ProtoMessage() {}

func (x *ListCalculatedFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCalculatedFieldsResponse.ProtoReflect.Descriptor instead.
func (*ListCalculatedFieldsResponse) Descriptor() ([]byte, []int) {
	return file_admin_proto_rawDescGZIP(), []int{27}
}

func (x *ListCalculatedFieldsResponse) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *ListCalculatedFieldsResponse) GetCalculatedFields() map[string]*CalculatedField {
	if x != nil {
		return x.CalculatedFields
	}
	return nil
}

var File_admin_proto protoreflect.FileDescriptor

const file_admin_proto_rawDesc = "" +
	"\n" +
	"\vadmin.proto\"\x9f\x01\n" +
	"\x05Error\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\bseverity\x18\x02 \x01(\x0e2\t.SeverityR\bseverity\x12:\n" +
	"\x16additional_information\x18\x03 \x01(\tH\x00R\x15additionalInformation\x88\x01\x01B\x19\n" +
	"\x17_additional_information\"\x99\x03\n" +
	"\x14CreateProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x121\n" +
	"\voutput_type\x18\n" +
	" \x01(\x0e2\v.OutputTypeH\x01R\n" +
	"outputType\x88\x01\x01\x12\x19\n" +
	"\x05named\x18\v \x01(\bH\x02R\x05named\x88\x01\x01\x12\x19\n" +
	"\x05array\x18\f \x01(\bH\x03R\x05array\x88\x01\x01\x125\n" +
	"\x14nested_property_name\x18\r \x01(\tH\x04R\x12nestedPropertyName\x88\x01\x01\x12!\n" +
	"\tseparator\x18\x0e \x01(\tH\x05R\tseparator\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_output_typeB\b\n" +
	"\x06_namedB\b\n" +
	"\x06_arrayB\x17\n" +
	"\x15_nested_property_nameB\f\n" +
	"\n" +
	"_separatorJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"\"S\n" +
	"\x15CreateProjectResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"0\n" +
	"\x14RemoveProjectRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"7\n" +
	"\x15RemoveProjectResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\"l\n" +
	"\x0fListProjectData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x15\n" +
	"\x13ListProjectsRequest\"d\n" +
	"\x14ListProjectsResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\x12,\n" +
	"\bprojects\x18\x02 \x03(\v2\x10.ListProjectDataR\bprojects\"Q\n" +
	"\x13ColumnConfiguration\x12\x1a\n" +
	"\bproperty\x18\x01 \x01(\tR\bproperty\x12\x1e\n" +
	"\x04type\x18\x02 \x01(\x0e2\n" +
	".FieldTypeR\x04type\"\xce\x01\n" +
	"\x19AddOrUpdateMappingRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12D\n" +
	"\bmappings\x18\x02 \x03(\v2(.AddOrUpdateMappingRequest.MappingsEntryR\bmappings\x1aQ\n" +
	"\rMappingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.ColumnConfigurationR\x05value:\x028\x01\"\xde\x01\n" +
	"\x1aAddOrUpdateMappingResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\x12Q\n" +
	"\fActionsTaken\x18\x02 \x03(\v2-.AddOrUpdateMappingResponse.ActionsTakenEntryR\fActionsTaken\x1aM\n" +
	"\x11ActionsTakenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\x0e2\f.ActionTakenR\x05value:\x028\x01\"/\n" +
	"\x13ListMappingsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"\xca\x01\n" +
	"\x14ListMappingsResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\x12?\n" +
	"\bmappings\x18\x02 \x03(\v2#.ListMappingsResponse.MappingsEntryR\bmappings\x1aQ\n" +
	"\rMappingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.ColumnConfigurationR\x05value:\x028\x01\"L\n" +
	"\x14RemoveMappingRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1a\n" +
	"\bmappings\x18\x02 \x03(\tR\bmappings\"7\n" +
	"\x15RemoveMappingResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\"\xcd\x01\n" +
	"\x17AddExtraVariableRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12U\n" +
	"\x0fextra_variables\x18\x02 \x03(\v2,.AddExtraVariableRequest.ExtraVariablesEntryR\x0eextraVariables\x1aA\n" +
	"\x13ExtraVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x18AddExtraVariableResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\"5\n" +
	"\x19ListExtraVariablesRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"\xd9\x01\n" +
	"\x1aListExtraVariablesResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\x12X\n" +
	"\x0fextra_variables\x18\x02 \x03(\v2/.ListExtraVariablesResponse.ExtraVariablesEntryR\x0eextraVariables\x1aA\n" +
	"\x13ExtraVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x1aRemoveExtraVariableRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12'\n" +
	"\x0fextra_variables\x18\x02 \x03(\tR\x0eextraVariables\"=\n" +
	"\x1bRemoveExtraVariableResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\"\x8b\x01\n" +
	"\x0fCalculatedField\x12\x19\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x05.KindR\x04kind\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1e\n" +
	"\x04type\x18\x03 \x01(\x0e2\n" +
	".FieldTypeR\x04type\x12%\n" +
	"\blocation\x18\x04 \x01(\x0e2\t.LocationR\blocation\"\xfd\x01\n" +
	"\"AddOrUpdateCalculatedFieldsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12f\n" +
	"\x11calculated_fields\x18\x02 \x03(\v29.AddOrUpdateCalculatedFieldsRequest.CalculatedFieldsEntryR\x10calculatedFields\x1aU\n" +
	"\x15CalculatedFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.CalculatedFieldR\x05value:\x028\x01\"E\n" +
	"#AddOrUpdateCalculatedFieldsResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\"f\n" +
	"\x1dRemoveCalculatedFieldsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12+\n" +
	"\x11calculated_fields\x18\x02 \x03(\tR\x10calculatedFields\"@\n" +
	"\x1eRemoveCalculatedFieldsResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\"7\n" +
	"\x1bListCalculatedFieldsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"\xf7\x01\n" +
	"\x1cListCalculatedFieldsResponse\x12\x1e\n" +
	"\x06errors\x18\x01 \x03(\v2\x06.ErrorR\x06errors\x12`\n" +
	"\x11calculated_fields\x18\x02 \x03(\v23.ListCalculatedFieldsResponse.CalculatedFieldsEntryR\x10calculatedFields\x1aU\n" +
	"\x15CalculatedFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.CalculatedFieldR\x05value:\x028\x01*-\n" +
	"\bSeverity\x12\b\n" +
	"\x04WARN\x10\x00\x12\f\n" +
	"\bCRITICAL\x10\x01\x12\t\n" +
	"\x05FATAL\x10\x02**\n" +
	"\n" +
	"OutputType\x12\b\n" +
	"\x04JSON\x10\x00\x12\b\n" +
	"\x04YAML\x10\x01\x12\b\n" +
	"\x04TOML\x10\x02*5\n" +
	"\tFieldType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\a\n" +
	"\x03INT\x10\x01\x12\t\n" +
	"\x05FLOAT\x10\x02\x12\b\n" +
	"\x04BOOL\x10\x03*%\n" +
	"\vActionTaken\x12\t\n" +
	"\x05ADDED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01*M\n" +
	"\x04Kind\x12\x0f\n" +
	"\vAPPLICATION\x10\x00\x12\f\n" +
	"\bDATETIME\x10\x01\x12\x0e\n" +
	"\n" +
	"ENVRINMENT\x10\x02\x12\t\n" +
	"\x05EXTRA\x10\x03\x12\v\n" +
	"\aMAPPING\x10\x04*$\n" +
	"\bLocation\x12\n" +
	"\n" +
	"\x06RECORD\x10\x00\x12\f\n" +
	"\bEOCUMENT\x10\x012\xdc\x06\n" +
	"\fAdminService\x12@\n" +
	"\rCreateProject\x12\x15.CreateProjectRequest\x1a\x16.CreateProjectResponse\"\x00\x12@\n" +
	"\rRemoveProject\x12\x15.RemoveProjectRequest\x1a\x16.RemoveProjectResponse\"\x00\x12=\n" +
	"\fListProjects\x12\x14.ListProjectsRequest\x1a\x15.ListProjectsResponse\"\x00\x12O\n" +
	"\x12AddOrUpdateMapping\x12\x1a.AddOrUpdateMappingRequest\x1a\x1b.AddOrUpdateMappingResponse\"\x00\x12@\n" +
	"\rRemoveMapping\x12\x15.RemoveMappingRequest\x1a\x16.RemoveMappingResponse\"\x00\x12=\n" +
	"\fListMappings\x12\x14.ListMappingsRequest\x1a\x15.ListMappingsResponse\"\x00\x12I\n" +
	"\x10AddExtraVariable\x12\x18.AddExtraVariableRequest\x1a\x19.AddExtraVariableResponse\"\x00\x12R\n" +
	"\x13RemoveExtraVariable\x12\x1b.RemoveExtraVariableRequest\x1a\x1c.RemoveExtraVariableResponse\"\x00\x12O\n" +
	"\x12ListExtraVariables\x12\x1a.ListExtraVariablesRequest\x1a\x1b.ListExtraVariablesResponse\"\x00\x12j\n" +
	"\x1bAddOrUpdateCalculatedFields\x12#.AddOrUpdateCalculatedFieldsRequest\x1a$.AddOrUpdateCalculatedFieldsResponse\"\x00\x12[\n" +
	"\x16RemoveCalculatedFields\x12\x1e.RemoveCalculatedFieldsRequest\x1a\x1f.RemoveCalculatedFieldsResponse\"\x00B)Z'github.com/sascha-andres/csv2json/adminb\x06proto3"

var (
	file_admin_proto_rawDescOnce sync.Once
	file_admin_proto_rawDescData []byte
)

func file_admin_proto_rawDescGZIP() []byte {
	file_admin_proto_rawDescOnce.Do(func() {
		file_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)))
	})
	return file_admin_proto_rawDescData
}

var file_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_admin_proto_goTypes = []any{
	(Severity)(0),                               // 0: Severity
	(OutputType)(0),                             // 1: OutputType
	(FieldType)(0),                              // 2: FieldType
	(ActionTaken)(0),                            // 3: ActionTaken
	(Kind)(0),                                   // 4: Kind
	(Location)(0),                               // 5: Location
	(*Error)(nil),                               // 6: Error
	(*CreateProjectRequest)(nil),                // 7: CreateProjectRequest
	(*CreateProjectResponse)(nil),               // 8: CreateProjectResponse
	(*RemoveProjectRequest)(nil),                // 9: RemoveProjectRequest
	(*RemoveProjectResponse)(nil),               // 10: RemoveProjectResponse
	(*ListProjectData)(nil),                     // 11: ListProjectData
	(*ListProjectsRequest)(nil),                 // 12: ListProjectsRequest
	(*ListProjectsResponse)(nil),                // 13: ListProjectsResponse
	(*ColumnConfiguration)(nil),                 // 14: ColumnConfiguration
	(*AddOrUpdateMappingRequest)(nil),           // 15: AddOrUpdateMappingRequest
	(*AddOrUpdateMappingResponse)(nil),          // 16: AddOrUpdateMappingResponse
	(*ListMappingsRequest)(nil),                 // 17: ListMappingsRequest
	(*ListMappingsResponse)(nil),                // 18: ListMappingsResponse
	(*RemoveMappingRequest)(nil),                // 19: RemoveMappingRequest
	(*RemoveMappingResponse)(nil),               // 20: RemoveMappingResponse
	(*AddExtraVariableRequest)(nil),             // 21: AddExtraVariableRequest
	(*AddExtraVariableResponse)(nil),            // 22: AddExtraVariableResponse
	(*ListExtraVariablesRequest)(nil),           // 23: ListExtraVariablesRequest
	(*ListExtraVariablesResponse)(nil),          // 24: ListExtraVariablesResponse
	(*RemoveExtraVariableRequest)(nil),          // 25: RemoveExtraVariableRequest
	(*RemoveExtraVariableResponse)(nil),         // 26: RemoveExtraVariableResponse
	(*CalculatedField)(nil),                     // 27: CalculatedField
	(*AddOrUpdateCalculatedFieldsRequest)(nil),  // 28: AddOrUpdateCalculatedFieldsRequest
	(*AddOrUpdateCalculatedFieldsResponse)(nil), // 29: AddOrUpdateCalculatedFieldsResponse
	(*RemoveCalculatedFieldsRequest)(nil),       // 30: RemoveCalculatedFieldsRequest
	(*RemoveCalculatedFieldsResponse)(nil),      // 31: RemoveCalculatedFieldsResponse
	(*ListCalculatedFieldsRequest)(nil),         // 32: ListCalculatedFieldsRequest
	(*ListCalculatedFieldsResponse)(nil),        // 33: ListCalculatedFieldsResponse
	nil,                                         // 34: AddOrUpdateMappingRequest.MappingsEntry
	nil,                                         // 35: AddOrUpdateMappingResponse.ActionsTakenEntry
	nil,                                         // 36: ListMappingsResponse.MappingsEntry
	nil,                                         // 37: AddExtraVariableRequest.ExtraVariablesEntry
	nil,                                         // 38: ListExtraVariablesResponse.ExtraVariablesEntry
	nil,                                         // 39: AddOrUpdateCalculatedFieldsRequest.CalculatedFieldsEntry
	nil,                                         // 40: ListCalculatedFieldsResponse.CalculatedFieldsEntry
}
var file_admin_proto_depIdxs = []int32{
	0,  // 0: Error.severity:type_name -> Severity
	1,  // 1: CreateProjectRequest.output_type:type_name -> OutputType
	6,  // 2: CreateProjectResponse.errors:type_name -> Error
	6,  // 3: RemoveProjectResponse.errors:type_name -> Error
	6,  // 4: ListProjectsResponse.errors:type_name -> Error
	11, // 5: ListProjectsResponse.projects:type_name -> ListProjectData
	2,  // 6: ColumnConfiguration.type:type_name -> FieldType
	34, // 7: AddOrUpdateMappingRequest.mappings:type_name -> AddOrUpdateMappingRequest.MappingsEntry
	6,  // 8: AddOrUpdateMappingResponse.errors:type_name -> Error
	35, // 9: AddOrUpdateMappingResponse.ActionsTaken:type_name -> AddOrUpdateMappingResponse.ActionsTakenEntry
	6,  // 10: ListMappingsResponse.errors:type_name -> Error
	36, // 11: ListMappingsResponse.mappings:type_name -> ListMappingsResponse.MappingsEntry
	6,  // 12: RemoveMappingResponse.errors:type_name -> Error
	37, // 13: AddExtraVariableRequest.extra_variables:type_name -> AddExtraVariableRequest.ExtraVariablesEntry
	6,  // 14: AddExtraVariableResponse.errors:type_name -> Error
	6,  // 15: ListExtraVariablesResponse.errors:type_name -> Error
	38, // 16: ListExtraVariablesResponse.extra_variables:type_name -> ListExtraVariablesResponse.ExtraVariablesEntry
	6,  // 17: RemoveExtraVariableResponse.errors:type_name -> Error
	4,  // 18: CalculatedField.kind:type_name -> Kind
	2,  // 19: CalculatedField.type:type_name -> FieldType
	5,  // 20: CalculatedField.location:type_name -> Location
	39, // 21: AddOrUpdateCalculatedFieldsRequest.calculated_fields:type_name -> AddOrUpdateCalculatedFieldsRequest.CalculatedFieldsEntry
	6,  // 22: AddOrUpdateCalculatedFieldsResponse.errors:type_name -> Error
	6,  // 23: RemoveCalculatedFieldsResponse.errors:type_name -> Error
	6,  // 24: ListCalculatedFieldsResponse.errors:type_name -> Error
	40, // 25: ListCalculatedFieldsResponse.calculated_fields:type_name -> ListCalculatedFieldsResponse.CalculatedFieldsEntry
	14, // 26: AddOrUpdateMappingRequest.MappingsEntry.value:type_name -> ColumnConfiguration
	3,  // 27: AddOrUpdateMappingResponse.ActionsTakenEntry.value:type_name -> ActionTaken
	14, // 28: ListMappingsResponse.MappingsEntry.value:type_name -> ColumnConfiguration
	27, // 29: AddOrUpdateCalculatedFieldsRequest.CalculatedFieldsEntry.value:type_name -> CalculatedField
	27, // 30: ListCalculatedFieldsResponse.CalculatedFieldsEntry.value:type_name -> CalculatedField
	7,  // 31: AdminService.CreateProject:input_type -> CreateProjectRequest
	9,  // 32: AdminService.RemoveProject:input_type -> RemoveProjectRequest
	12, // 33: AdminService.ListProjects:input_type -> ListProjectsRequest
	15, // 34: AdminService.AddOrUpdateMapping:input_type -> AddOrUpdateMappingRequest
	19, // 35: AdminService.RemoveMapping:input_type -> RemoveMappingRequest
	17, // 36: AdminService.ListMappings:input_type -> ListMappingsRequest
	21, // 37: AdminService.AddExtraVariable:input_type -> AddExtraVariableRequest
	25, // 38: AdminService.RemoveExtraVariable:input_type -> RemoveExtraVariableRequest
	23, // 39: AdminService.ListExtraVariables:input_type -> ListExtraVariablesRequest
	28, // 40: AdminService.AddOrUpdateCalculatedFields:input_type -> AddOrUpdateCalculatedFieldsRequest
	30, // 41: AdminService.RemoveCalculatedFields:input_type -> RemoveCalculatedFieldsRequest
	8,  // 42: AdminService.CreateProject:output_type -> CreateProjectResponse
	10, // 43: AdminService.RemoveProject:output_type -> RemoveProjectResponse
	13, // 44: AdminService.ListProjects:output_type -> ListProjectsResponse
	16, // 45: AdminService.AddOrUpdateMapping:output_type -> AddOrUpdateMappingResponse
	20, // 46: AdminService.RemoveMapping:output_type -> RemoveMappingResponse
	18, // 47: AdminService.ListMappings:output_type -> ListMappingsResponse
	22, // 48: AdminService.AddExtraVariable:output_type -> AddExtraVariableResponse
	26, // 49: AdminService.RemoveExtraVariable:output_type -> RemoveExtraVariableResponse
	24, // 50: AdminService.ListExtraVariables:output_type -> ListExtraVariablesResponse
	29, // 51: AdminService.AddOrUpdateCalculatedFields:output_type -> AddOrUpdateCalculatedFieldsResponse
	31, // 52: AdminService.RemoveCalculatedFields:output_type -> RemoveCalculatedFieldsResponse
	42, // [42:53] is the sub-list for method output_type
	31, // [31:42] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_admin_proto_init() }
func file_admin_proto_init() {
	if File_admin_proto != nil {
		return
	}
	file_admin_proto_msgTypes[0].OneofWrappers = []any{}
	file_admin_proto_msgTypes[1].OneofWrappers = []any{}
	file_admin_proto_msgTypes[2].OneofWrappers = []any{}
	file_admin_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_proto_rawDesc), len(file_admin_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_proto_goTypes,
		DependencyIndexes: file_admin_proto_depIdxs,
		EnumInfos:         file_admin_proto_enumTypes,
		MessageInfos:      file_admin_proto_msgTypes,
	}.Build()
	File_admin_proto = out.File
	file_admin_proto_goTypes = nil
	file_admin_proto_depIdxs = nil
}
