name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'I agree to the CLA' || github.event.comment.body == 'recheck') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'signatures/cla.json'
          path-to-document: 'https://github.com/${{ github.repository }}/blob/main/CONTRIBUTING.md'
          branch: 'main'
          allowlist: bot*
          empty-commit-flag: false
          blockchain-storage-flag: false
          signed-commit-message: 'Signed CLA'
          custom-notsigned-prcomment: 'Thank you for your contribution! Before we can merge this pull request, we need you to agree to our Contributor License Agreement (CLA). Please read the CLA in the [CONTRIBUTING.md](https://github.com/${{ github.repository }}/blob/main/CONTRIBUTING.md) file and comment on this PR with the phrase "I agree to the CLA" to indicate your agreement.'
          custom-pr-sign-comment: 'I agree to the CLA'
          create-file-commit-message: 'Creating file for storing CLA signatures'
          lock-pullrequest-aftermerge: false
          use-dco-flag: false